---
- name: deploy task for commandline
  copy:
    src: "{{ path }}/target/{{ bundle }}"
    dest: "{{ dspace_lib }}"
    remote_src: true
  when: state == 'present'

- name: remove task from commandline
  file:
    dest: "{{ dspace_lib }}/{{ bundle }}"
    state: "{{ state }}"
  when: state == 'absent'

- block:
  - name: deploy task for ui
    copy:
      src: "{{ path }}/target/{{ bundle }}"
      dest: "{{ dspace_xmlui_lib }}"
      remote_src: true
    when: state == 'present'

  - name: remove task from ui
    file:
      dest: "{{ dspace_xmlui_lib }}/{{ bundle }}"
      state: "{{ state }}"
    when: state == 'absent'
  when: ui_taskname != ''
